---
- name: Deploy container with docker
  hosts: all
  vars_files:
    - ../vault.yml

  tasks:
    - name: Deploy Node RED Server
      community.docker.docker_container:
        name: Node-RED
        image: nodered/node-red:latest
        state: started
        restart: true
        ports:
          # Publish container port 9000 as host port 8080
          - "1880:1880"
          # Publish container UDP port 9001 as host port 8081 on interface 127.0.0.1
          #- "127.0.0.1:8081:9001/udp"
          # Publish container port 9002 as a random host port
          #- "9002"
          # Publish container port 9003 as a free host port in range 8000-8100
          # (the host port will be selected by the Docker daemon)
          #- "8000-8100:9003"
          # Publish container ports 9010-9020 to host ports 7000-7010
          #- "7000-7010:9010-9020"
        volumes:
          - node_red_data:/data
        env:
          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
          TZ: "Europe/Berlin"
        security_opts:
          "seccomp=unconfined"
    - name: Deploy EMQX MQTT Server
      community.docker.docker_container:
        name: EMQX
        image: emqx/emqx:4.2.14
        state: started
        restart: true
        ports:
          # Publish container port 9000 as host port 8080
          - "1883:1883"
          - "18083:18083"
          - "8083:8083"
          - "4369:4369"
          - "5369:5369"
          - "6369:6369"
          # Publish container UDP port 9001 as host port 8081 on interface 127.0.0.1
          #- "127.0.0.1:8081:9001/udp"
          # Publish container port 9002 as a random host port
          #- "9002"
          # Publish container port 9003 as a free host port in range 8000-8100
          # (the host port will be selected by the Docker daemon)
          #- "8000-8100:9003"
          # Publish container ports 9010-9020 to host ports 7000-7010
          #- "7000-7010:9010-9020"
        volumes:
          - emqx-data:/opt/emqx/data
          - emqx-etc:/opt/emqx/etc
          - emqx-log:/opt/emqx/log
        env:
          # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
          EMQX_NODE__COOKIE: "somepw"
          EMQX_RETAINER__EXPIRY_INTERVAL: "7s"
          EMQX_OS_MON__CPU_HIGH_WATERMARK: "100%"
          EMQX_LOG__TO: "console"
          EMQX_LISTENER__TCP__INTERNAL: "127.0.0.1:11883"

