---
- hosts: localhost
  vars_files:
    - ../vault.yml

  tasks:
    - name: Generate an OpenSSH keypair for remote user (ssh-ed25519)
      openssh_keypair:
        path: ~/.ssh/id_ssh_ed25519_{{ item[0] }}_{{ item[1] }}
        type: ed25519
      with_nested: 
        - "{{ users }}"
        - "{{ hosts.split(',') }}"
